DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS post;
DROP TABLE IF EXISTS mensajes;
DROP TABLE IF EXISTS bitacora;

CREATE TABLE users(
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE post (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  author_id INTEGER NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  title TEXT NOT NULL,
  body TEXT NOT NULL,
  FOREIGN KEY (author_id) REFERENCES user (id)
);

CREATE TABLE mensajes (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    id_emisor INTEGER NOT NULL,
    id_receptor INTEGER NOT NULL,
    titulo TEXT NOT NULL,
    mensaje TEXT NOT NULL,
    enviado DATETIME NULL,
    recibido DATETIME NULL
);

CREATE TABLE bitacora (
    id  INTEGER PRIMARY KEY AUTOINCREMENT,
    id_mensaje INTEGER NOT NULL,
    fecha DATETIME NOT NULL,
    accion TEXT NOT NULL
);